name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      uses: vvish/install-gtest-gmock@v1
      with:
        gmock: true
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run tests and produce code coverage
      run: make code-coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
